### ISSUE TITLE
uninitialized constant MultiBinder:UNIXSocket

### ISSUE THREAD

**Issue by sylvek** [github/multibinder#3]
Hi,

i do a test of multibinder, but i have actually an error…

```
vagrant@debian-jessie:~$ MULTIBINDER_SOCK=multibinder.sock ruby bridge.rb 
/home/vagrant/.rbenv/versions/2.2.0-preview1/lib/ruby/gems/2.2.0/gems/multibinder-0.0.4/lib/multibinder.rb:8:in `bind': uninitialized constant MultiBinder::UNIXSocket (NameError)
	from bridge.rb:3:in `<main>'
```

my bridge.rb looks like that

```
require 'multibinder'

server = MultiBinder.bind '127.0.0.1', 2000

pid = Process.spawn "ruby server.rb", :close_others => false

Signal.trap("INT") { Process.kill "USR1", pid }
Signal.trap("TERM") { Process.kill "USR1", pid }

Process.waitpid
```

my server.rb is just a simple echo over tcp

```
require 'socket'

server = TCPServer.new 2000 # Server bound to port 2000

loop do
  client = server.accept    # Wait for a client to connect
  client.puts "Hello !"
  client.puts "Time is #{Time.now}"
  client.close
end
```

my goal is to launch a jetty server instead, it is why i test via a Process.spawn.

oc, i before launched…

```
vagrant@debian-jessie:~$ multibinder multibinder.sock
Listening for binds on control socket: multibinder.sock
```

where is my failure ? :-!

**Comment by jbarnette** [comment]
@sylvek Hi! Try `require "socket"` in your `bridge.rb`. multifinder requires it [in `bin/multibinder`](https://github.com/github/multibinder/blob/1c67e87322ffca0cec310ef3bd4cd1ac4f38189b/bin/multibinder#L3) but not [in `lib/multibinder.rb`](https://github.com/github/multibinder/blob/1c67e87322ffca0cec310ef3bd4cd1ac4f38189b/lib/multibinder.rb#L8).

**Comment by sylvek** [comment]
hi @jbarnette thank you for your answer.
i have tried what you advice me…

i'm little confused because i took a very simple sample and i didn't see some requirement and now, i have an another error

```
vagrant@debian-jessie:~$ MULTIBINDER_SOCK=multibinder.sock ruby bridge.rb 
/home/vagrant/.rbenv/versions/2.2.0-preview1/lib/ruby/gems/2.2.0/gems/multibinder-0.0.4/lib/multibinder.rb:30:in `bind': uninitialized constant MultiBinder::Fcntl (NameError)
	from bridge.rb:4:in `<main>'
```

and from server side…

```
vagrant@debian-jessie:~$ multibinder multibinder.sock
Listening for binds on control socket: multibinder.sock
Request: {"jsonrpc"=>"2.0", "method"=>"bind", "params"=>[{"address"=>"127.0.0.1", "port"=>2000}]}
```

**Comment by sylvek** [comment]
by adding require 'fcntl', it fixes the issue.

**Comment by sylvek** [comment]
👍

**Comment by djMax** [comment]
I needed both require 'fcntl' and require 'socket'...
